services:
  - type: web
    name: disease-prediction-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
